name: Deploy API to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.18.2
          run_install: true
      - uses: cloudflare/wrangler-action@2.0.0
        name: Deploy API to Cloudflare Workers
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api